language: generic

sudo: required
dist: trusty

# Blacklist
branches:
  except:
    - gh-pages

python:
  - "3.6"

before_install:
  - bash .travis/before_install.sh
  # setup git
  - git config --local user.name "embARC"
  - git config --local user.email "embarc@embarc.org"

script:
  - bash .travis/script.sh

matrix:
  include:
    - env: TOOLCHAIN="sphinx" BOARD="none" BD_VER="none" CUR_CORE="none"
      os: linux
    - env: TOOLCHAIN="gnu" BOARD="emsk" BD_VER="11" CUR_CORE="arcem4"
      os: linux
      compiler: gcc
    - env: TOOLCHAIN="gnu" BOARD="emsk" BD_VER="11" CUR_CORE="arcem6"
      os: linux
      compiler: gcc
    - env: TOOLCHAIN="gnu" BOARD="emsk" BD_VER="22" CUR_CORE="arcem7d"
      os: linux
      compiler: gcc
    - env: TOOLCHAIN="gnu" BOARD="emsk" BD_VER="22" CUR_CORE="arcem9d"
      os: linux
      compiler: gcc
    - env: TOOLCHAIN="gnu" BOARD="emsk" BD_VER="22" CUR_CORE="arcem11d"
      os: linux
      compiler: gcc
    - env: TOOLCHAIN="gnu" BOARD="emsk" BD_VER="23" CUR_CORE="arcem7d"
      os: linux
      compiler: gcc
    - env: TOOLCHAIN="gnu" BOARD="emsk" BD_VER="23" CUR_CORE="arcem9d"
      os: linux
      compiler: gcc
    - env: TOOLCHAIN="gnu" BOARD="emsk" BD_VER="23" CUR_CORE="arcem11d"
      os: linux
      compiler: gcc
    - env: TOOLCHAIN="gnu" BOARD="hsdk" BD_VER="10" CUR_CORE="archs38_c0"
      os: linux
      compiler: gcc
